"""
interfaces.py
Contratos (Protocols) de los repositorios de VorTrack.

Las capas altas (servicios y UI) dependerán de estos tipos abstractos y no de
las clases concretas (Inversión de Dependencias). Al ser `Protocol`, cualquier
repositorio que tenga estos métodos los satisface sin herencia explícita.
"""

from typing import Any, Optional, Protocol, Sequence

Fila = Any
Filas = Sequence[Any]


class RepoUsuariosProto(Protocol):
    def buscar_para_login(self, usuario: str) -> Optional[Fila]: ...
    def listar_estudiantes(self) -> Filas: ...
    def crear_estudiante(self, nombres, apellidos, correo, telefono, contrasena) -> int: ...
    def actualizar_estudiante(self, id_usuario, nombres, apellidos, correo, telefono, contrasena, estado) -> None: ...
    def eliminar_estudiante(self, id_usuario) -> None: ...


class RepoJornadasProto(Protocol):
    def listar_para_combo(self) -> Filas: ...
    def peso_pet(self, id_jornada) -> float: ...
    def crear(self, fecha, id_lugar, id_responsable, cantidad_botellas, peso_pet, observaciones) -> int: ...
    def recientes(self, limite: int = 50) -> Filas: ...
    def listar_admin(self, limite: int = 300) -> Filas: ...
    def obtener(self, id_jornada) -> Optional[Fila]: ...
    def actualizar(self, id_jornada, fecha, id_lugar, id_responsable, botellas, peso, obs) -> None: ...
    def eliminar(self, id_jornada) -> None: ...


class RepoProduccionProto(Protocol):
    def listar_para_combo(self) -> Filas: ...
    def crear(self, id_jornada, fecha, color, diametro, peso_obtenido, metros, observaciones) -> int: ...
    def recientes(self, limite: int = 50) -> Filas: ...
    def listar_admin(self, limite: int = 300) -> Filas: ...
    def obtener(self, id_produccion) -> Optional[Fila]: ...
    def actualizar(self, id_produccion, id_jornada, fecha, color, diametro, peso_obtenido, metros, obs) -> None: ...
    def eliminar(self, id_produccion) -> None: ...


class RepoFabricacionProto(Protocol):
    def crear(self, id_modelo, id_produccion, fecha, cantidad, peso_utilizado, tiempo_min, estado) -> int: ...
    def recientes(self, limite: int = 50) -> Filas: ...
    def listar_admin(self, limite: int = 300) -> Filas: ...
    def obtener(self, id_fab) -> Optional[Fila]: ...
    def actualizar(self, id_fab, id_modelo, id_produccion, fecha, cantidad, peso, tiempo, estado) -> None: ...
    def eliminar(self, id_fab) -> None: ...


class RepoLugaresProto(Protocol):
    def listar(self) -> Filas: ...
    def listar_admin(self) -> Filas: ...
    def crear(self, nombre, descripcion) -> int: ...
    def actualizar(self, id_lugar, nombre, descripcion) -> None: ...
    def eliminar(self, id_lugar) -> None: ...


class RepoModelosProto(Protocol):
    def listar(self) -> Filas: ...
    def listar_admin(self) -> Filas: ...
    def crear(self, nombre, categoria, tiempo_estimado, peso_estimado) -> int: ...
    def actualizar(self, id_modelo, nombre, categoria, tiempo_estimado, peso_estimado) -> None: ...
    def eliminar(self, id_modelo) -> None: ...


class RepoResponsablesProto(Protocol):
    def listar(self) -> Filas: ...


class RepoIndicadoresProto(Protocol):
    def resumen(self) -> dict: ...
    def ranking(self, limite: int = 10) -> Filas: ...
